server:
  port: 9988
spring:
  application:
    name: springbok
  mvc:
    hiddenmethod:
      # 启用HiddenHttpMethodFilter使其先进行解析，解决读取不到输入流的问题
      filter:
        enabled: true
  profiles:
    # 选择配置文件
    active: dev
  # spring-boot-admin客户端配置
  boot:
    admin:
      client:
        # 访问springbok-monitor监控服务地址
        url: http://localhost:9989
        # 访问springbok-monitor监控服务的用户名
        username: admin
        # 访问springbok-monitor监控服务的密码
        password: 123456
        # 本应用实例服务地址
        instance:
          service-url: http://localhost:9988
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      # 配置暴露的端点，可指定特定的端口id，'*'表示暴露所有端点
      exposure:
        include: '*'
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Springbok-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
springdoc:
  # 文档分组
  group-configs:
    - group: system
      display-name: "管理后台接口文档"
      paths-to-match: '/**'
      packages-to-scan: cn.code4java.springbok.controller
